### ISSUE TITLE
Temporal Negative Sampling roadmap

### ISSUE THREAD

**Issue by VaghehDashti** [fani-lab/OpeNTF#206]
Here are the tasks for development and publishing the paper for temporal negative sampling for NTF:
1. Literature review:
- [x] [Curriculum Learning ](https://dl.acm.org/doi/10.1145/1553374.1553380)  https://github.com/fani-lab/OpeNTF/issues/208
- [ ] [Curriculum Learning: A Survey](https://arxiv.org/abs/2101.10382)
- [ ] ...

2. Conducting experiments:
- [x] Implementing temporal negative sampling
- [x] Running on toy datasets 
- [ ] Running on dblp
- [ ] Running on imdb
- [ ] Running on uspt
- [ ] Running on gith

3. Paper write up:
- [ ] Abstract
- [x] Introduction
- [x] Literature review
- [x] Problem definition
- [ ] Methodologies
- [ ] Experiments and results
- [ ] Conclusion

Please note that this is not final and will be updated as needed.

**Comment by hosseinfani** [comment]
probably we'll continue with #275
